<?php

namespace AppBundle\Repository;

/**
 * AboutusimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutusimageRepository extends \Doctrine\ORM\EntityRepository
{
}
