<?php

namespace AppBundle\Repository;

/**
 * BuimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuimageRepository extends \Doctrine\ORM\EntityRepository
{
}
