<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
    * Return number rows of Category
    */
    public function getRows() {
      $query = $this->getEntityManager()
			->createQuery('SELECT c FROM
    			AppBundle:Category c
      ');
      $rq = $query->getResult();
      return count($rq);
    }
}
