<?php

namespace AppBundle\Repository;

/**
 * CsrimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsrimageRepository extends \Doctrine\ORM\EntityRepository
{
}
