<?php

namespace AppBundle\Repository;

/**
 * CsrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsrRepository extends \Doctrine\ORM\EntityRepository
{
}
