<?php

namespace AppBundle\Repository;

/**
 * LogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogoRepository extends \Doctrine\ORM\EntityRepository
{
}
