<?php

namespace AppBundle\Repository;

/**
 * MontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontRepository extends \Doctrine\ORM\EntityRepository
{
}
