<?php

namespace AppBundle\Repository;

/**
 * MonthnewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonthnewsRepository extends \Doctrine\ORM\EntityRepository
{
}
