<?php

namespace AppBundle\Repository;

/**
 * OverviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverviewRepository extends \Doctrine\ORM\EntityRepository
{
}
