<?php

namespace AppBundle\Repository;

/**
 * PeoplesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeoplesRepository extends \Doctrine\ORM\EntityRepository
{
  /**
  * Return number rows of Peoples
  */
  public function getRows() {
    $query = $this->getEntityManager()
    ->createQuery('SELECT p FROM
        AppBundle:Peoples p where p.id != 1
    ');
    $rq = $query->getResult();
    return count($rq);
  }
}
