<?php

namespace AppBundle\Repository;

/**
 * UnitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitesRepository extends \Doctrine\ORM\EntityRepository
{
}
