<?php

namespace AppBundle\Repository;

/**
 * YearnewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearnewsRepository extends \Doctrine\ORM\EntityRepository
{
}
