<?php

namespace AppBundle\Repository;

/**
 * YearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearRepository extends \Doctrine\ORM\EntityRepository
{
}
