security:
    encoders:
        AppBundle\Entity\Users: sha512

    role_hierarchy:
        ROLE_USER: ROLE_ADMIN
        ROLE_USER: ROLE_USER

    providers:
        user:
            entity: { class: AppBundle:Users, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                always_use_default_target_path: false
                default_target_path: /admin
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ ROLE_USER, ROLE_ADMIN ] }
        # - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
