category_index:
    path:     /admin/category/
    defaults: { _controller: "AppBundle:Category:index" }
    methods:  GET

category_show:
    path:     /admin/category/{id}/show
    defaults: { _controller: "AppBundle:Category:show" }
    methods:  GET

category_new:
    path:     /admin/category/new
    defaults: { _controller: "AppBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /admin/category/{id}/edit
    defaults: { _controller: "AppBundle:Category:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /admin/category/{id}/delete
    defaults: { _controller: "AppBundle:Category:delete" }
    methods:  DELETE
