admin_colour:
    path:     /
    defaults: { _controller: "AppBundle:Colour:index" }

admin_colour_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Colour:show" }

admin_colour_new:
    path:     /new
    defaults: { _controller: "AppBundle:Colour:new" }

admin_colour_create:
    path:     /create
    defaults: { _controller: "AppBundle:Colour:create" }
    methods:  POST

admin_colour_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Colour:edit" }

admin_colour_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Colour:update" }
    methods:  [POST, PUT]

admin_colour_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Colour:delete" }
    methods:  [POST, DELETE]
