news_index:
    path:     /admin/news/
    defaults: { _controller: "AppBundle:News:index" }
    methods:  GET

news_index_public:
    path:     /news/
    defaults: { _controller: "AppBundle:News:indexPublic" }
    methods:  GET

news_show:
    path:     /admin/news/{id}/show
    defaults: { _controller: "AppBundle:News:show" }
    methods:  GET

news_show_public:
    path:     /news/{id}/showing
    defaults: { _controller: "AppBundle:News:showPublic" }
    methods:  GET

news_new:
    path:     /admin/news/new
    defaults: { _controller: "AppBundle:News:new" }
    methods:  [GET, POST]

news_edit:
    path:     /admin/news/{id}/edit
    defaults: { _controller: "AppBundle:News:edit" }
    methods:  [GET, POST]

news_delete:
    path:     /admin/news/{id}/delete
    defaults: { _controller: "AppBundle:News:delete" }
    methods:  DELETE
