year:
    path:     /
    defaults: { _controller: "AppBundle:Year:index" }

year_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Year:show" }

year_new:
    path:     /new
    defaults: { _controller: "AppBundle:Year:new" }

year_create:
    path:     /create
    defaults: { _controller: "AppBundle:Year:create" }
    requirements: { _method: post }

year_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Year:edit" }

year_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Year:update" }
    requirements: { _method: post|put }

year_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Year:delete" }
    requirements: { _method: post|delete }
