AppBundle\Entity\Career:
 type: entity
 table: career
 repositoryClass: AppBundle\Repository\CareerRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
  email:
   type: string
  title:
   type: string
  message:
   type: text
