AppBundle\Entity\Category:
 type: entity
 table: category
 repositoryClass: AppBundle\Repository\CategoryRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  category:
   type: string
 oneToMany:
  unites:
   targetEntity: Unites
   orphanRemoval: true
   mappedBy: category
