AppBundle\Entity\Logo:
 type: entity
 table: logo
 repositoryClass: AppBundle\Repository\LogoRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  largeImage:
   type: string
  createdAt:
   type: datetime
