AppBundle\Entity\Overview:
 type: entity
 table: overview
 repositoryClass: AppBundle\Repository\OverviewRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  overview:
   type: text
  mainAddress:
   type: text
