AppBundle\Entity\Peoples:
 type: entity
 table: peoples
 repositoryClass: AppBundle\Repository\PeoplesRepository
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  name:
   type: string
  position:
   type: string
  story:
   type: text
  largeImage:
   type: string
   nullable: true
