AppBundle\Entity\Users:
 type: entity
 repositoryClass: AppBundle\Repository\UserRepository
 table: users
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  is_admin:
   type: boolean
   nullable: true
  roles:
   type: json_array
   nullable: true
  username:
   type: string
   length: 255
   unique: true
  password:
   type: string
  salt:
   type: string
  is_active:
   type: boolean
   default: true
